## -*- encoding: utf-8 -*-

# This file was *autogenerated* from the file factoringCoefficients-Practice1.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_135 = Integer(135); _sage_const_111 = Integer(111); _sage_const_138 = Integer(138); _sage_const_114 = Integer(114); _sage_const_13 = Integer(13); _sage_const_12 = Integer(12); _sage_const_11 = Integer(11); _sage_const_10 = Integer(10); _sage_const_15 = Integer(15); _sage_const_14 = Integer(14); _sage_const_54 = Integer(54); _sage_const_123 = Integer(123); _sage_const_99 = Integer(99); _sage_const_126 = Integer(126); _sage_const_102 = Integer(102)## This file (factoringCoefficients-Practice1.sagetex.sage) was *autogenerated* from factoringCoefficients-Practice1.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('factoringCoefficients-Practice1', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.current_tex_line = _sage_const_6 
_st_.blockbegin()
try:
 def RandInt(a,b):
     """ Returns a random integer in [`a`,`b`]. Note that `a` and `b` should be integers themselves to avoid unexpected behavior.
     """
     return QQ(randint(int(a),int(b)))
     # return choice(range(a,b+1))
 
 def NonZeroInt(b,c, avoid = [_sage_const_0 ]):
     """ Returns a random integer in [`b`,`c`] which is not in `av`.
         If `av` is not specified, defaults to a non-zero integer.
     """
     while True:
         a = RandInt(b,c)
         if a not in avoid:
             return a
 
 ###### Problem p1
 p1c1 = RandInt(-_sage_const_10 ,_sage_const_10 )
 p1c2 = RandInt(-_sage_const_10 ,_sage_const_10 )
 p1f1 = x+p1c1
 p1f2 = x+p1c2
 p1f3 = (p1f1).mul(p1f2,hold=true)
 p1f4 = expand(p1f3)
 
 ###### Problem p2
 p2c1 = RandInt(-_sage_const_10 ,_sage_const_10 )
 p2c2 = RandInt(-_sage_const_10 ,_sage_const_10 )
 p2f1 = x+p2c1
 p2f2 = x+p2c2
 p2f3 = (p2f1).mul(p2f2,hold=true)
 p2f4 = expand(p2f3)
 
 ###### Problem p3
 p3c1 = RandInt(-_sage_const_10 ,_sage_const_10 )
 p3c2 = RandInt(-_sage_const_10 ,_sage_const_10 )
 p3f1 = x+p3c1
 p3f2 = x+p3c2
 p3f3 = (p3f1).mul(p3f2,hold=true)
 p3f4 = expand(p3f3)
 
 ###### Problem p4
 p4c1 = RandInt(-_sage_const_10 ,_sage_const_10 )
 p4c2 = RandInt(-_sage_const_10 ,_sage_const_10 )
 p4f1 = x+p4c1
 p4f2 = x+p4c2
 p4f3 = (p4f1).mul(p4f2,hold=true)
 p4f4 = expand(p4f3)
 
except:
 _st_.goboom(_sage_const_54 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_99 
 _st_.inline(_sage_const_0 , latex(p1f4))
except:
 _st_.goboom(_sage_const_99 )
try:
 _st_.current_tex_line = _sage_const_99 
 _st_.inline(_sage_const_1 , latex(p1f3))
except:
 _st_.goboom(_sage_const_99 )
try:
 _st_.current_tex_line = _sage_const_102 
 _st_.inline(_sage_const_2 , latex(p1c1*p1c2))
except:
 _st_.goboom(_sage_const_102 )
try:
 _st_.current_tex_line = _sage_const_102 
 _st_.inline(_sage_const_3 , latex(p1c1+p1c2))
except:
 _st_.goboom(_sage_const_102 )
try:
 _st_.current_tex_line = _sage_const_111 
 _st_.inline(_sage_const_4 , latex(p2f4))
except:
 _st_.goboom(_sage_const_111 )
try:
 _st_.current_tex_line = _sage_const_111 
 _st_.inline(_sage_const_5 , latex(p2f3))
except:
 _st_.goboom(_sage_const_111 )
try:
 _st_.current_tex_line = _sage_const_114 
 _st_.inline(_sage_const_6 , latex(p2c1*p2c2))
except:
 _st_.goboom(_sage_const_114 )
try:
 _st_.current_tex_line = _sage_const_114 
 _st_.inline(_sage_const_7 , latex(p2c1+p2c2))
except:
 _st_.goboom(_sage_const_114 )
try:
 _st_.current_tex_line = _sage_const_123 
 _st_.inline(_sage_const_8 , latex(p3f4))
except:
 _st_.goboom(_sage_const_123 )
try:
 _st_.current_tex_line = _sage_const_123 
 _st_.inline(_sage_const_9 , latex(p3f3))
except:
 _st_.goboom(_sage_const_123 )
try:
 _st_.current_tex_line = _sage_const_126 
 _st_.inline(_sage_const_10 , latex(p3c1*p3c2))
except:
 _st_.goboom(_sage_const_126 )
try:
 _st_.current_tex_line = _sage_const_126 
 _st_.inline(_sage_const_11 , latex(p3c1+p3c2))
except:
 _st_.goboom(_sage_const_126 )
try:
 _st_.current_tex_line = _sage_const_135 
 _st_.inline(_sage_const_12 , latex(p4f4))
except:
 _st_.goboom(_sage_const_135 )
try:
 _st_.current_tex_line = _sage_const_135 
 _st_.inline(_sage_const_13 , latex(p4f3))
except:
 _st_.goboom(_sage_const_135 )
try:
 _st_.current_tex_line = _sage_const_138 
 _st_.inline(_sage_const_14 , latex(p4c1*p4c2))
except:
 _st_.goboom(_sage_const_138 )
try:
 _st_.current_tex_line = _sage_const_138 
 _st_.inline(_sage_const_15 , latex(p4c1+p4c2))
except:
 _st_.goboom(_sage_const_138 )
_st_.endofdoc()

