## -*- encoding: utf-8 -*-

# This file was *autogenerated* from the file FTA-Practice1.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_182 = Integer(182); _sage_const_28 = Integer(28); _sage_const_213 = Integer(213); _sage_const_23 = Integer(23); _sage_const_22 = Integer(22); _sage_const_207 = Integer(207); _sage_const_20 = Integer(20); _sage_const_21 = Integer(21); _sage_const_26 = Integer(26); _sage_const_27 = Integer(27); _sage_const_24 = Integer(24); _sage_const_25 = Integer(25); _sage_const_134 = Integer(134); _sage_const_131 = Integer(131); _sage_const_170 = Integer(170); _sage_const_154 = Integer(154); _sage_const_176 = Integer(176); _sage_const_178 = Integer(178); _sage_const_215 = Integer(215); _sage_const_190 = Integer(190); _sage_const_196 = Integer(196); _sage_const_219 = Integer(219); _sage_const_13 = Integer(13); _sage_const_12 = Integer(12); _sage_const_11 = Integer(11); _sage_const_10 = Integer(10); _sage_const_17 = Integer(17); _sage_const_16 = Integer(16); _sage_const_15 = Integer(15); _sage_const_14 = Integer(14); _sage_const_19 = Integer(19); _sage_const_18 = Integer(18); _sage_const_160 = Integer(160); _sage_const_146 = Integer(146); _sage_const_29 = Integer(29); _sage_const_140 = Integer(140); _sage_const_142 = Integer(142); _sage_const_233 = Integer(233); _sage_const_227 = Integer(227)## This file (FTA-Practice1.sagetex.sage) was *autogenerated* from FTA-Practice1.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('FTA-Practice1', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.current_tex_line = _sage_const_8 
_st_.blockbegin()
try:
 def RandInt(a,b):
     """ Returns a random integer in [`a`,`b`]. Note that `a` and `b` should be integers themselves to avoid unexpected behavior.
     """
     return QQ(randint(int(a),int(b)))
     # return choice(range(a,b+1))
 
 def NonZeroInt(b,c, avoid = [_sage_const_0 ]):
     """ Returns a random integer in [`b`,`c`] which is not in `av`.
         If `av` is not specified, defaults to a non-zero integer.
     """
     while True:
         a = RandInt(b,c)
         if a not in avoid:
             return a
 
 
 #### Problem p1
 p1c1 = RandInt(_sage_const_1 ,_sage_const_10 )
 p1c2 = RandInt(_sage_const_1 ,_sage_const_10 )
 p1c3 = RandInt(_sage_const_1 ,_sage_const_10 )
 p1c4 = RandInt(_sage_const_1 ,_sage_const_10 )
 
 p1pwr1 = RandInt(_sage_const_1 ,_sage_const_10 )
 p1pwr2 = RandInt(_sage_const_1 ,_sage_const_10 )
 p1pwr3 = RandInt(_sage_const_1 ,_sage_const_10 )
 p1pwr4 = RandInt(_sage_const_1 ,_sage_const_10 )
 
 p1f1 = p1c1*x**p1pwr1
 p1f2 = p1c2*x**p1pwr2
 p1f3 = p1c3*x**p1pwr3
 p1f4 = p1c4*x**p1pwr4
 
 p1ans1 = max(p1pwr1,p1pwr2,p1pwr3,p1pwr4)
 
 # Followup for p1
 p1ans2 = _sage_const_0 
 p1ans3 = _sage_const_0 
 if p1pwr1 == p1ans1:
     p1ans2 = p1ans2 + p1f1
     p1ans3 = p1ans3 + p1c1
 if p1pwr2 == p1ans1:
     p1ans2 = p1ans2 + p1f2
     p1ans3 = p1ans3 + p1c2
 if p1pwr3 == p1ans1:
     p1ans2 = p1ans2 + p1f3
     p1ans3 = p1ans3 + p1c3
 if p1pwr4 == p1ans1:
     p1ans2 = p1ans2 + p1f4
     p1ans3 = p1ans3 + p1c4
 
 
 #### Problem p2
 p2c1 = RandInt(_sage_const_1 ,_sage_const_10 )
 p2c2 = RandInt(_sage_const_1 ,_sage_const_10 )
 p2c3 = RandInt(_sage_const_1 ,_sage_const_10 )
 p2c4 = RandInt(_sage_const_1 ,_sage_const_10 )
 
 p2pwr1 = RandInt(_sage_const_1 ,_sage_const_10 )
 p2pwr2 = RandInt(_sage_const_1 ,_sage_const_10 )
 p2pwr3 = RandInt(_sage_const_1 ,_sage_const_10 )
 p2pwr4 = RandInt(_sage_const_1 ,_sage_const_10 )
 
 p2f1 = p2c1*x**p2pwr1
 p2f2 = p2c2*x**p2pwr2
 p2f3 = p2c3*x**p2pwr3
 p2f4 = p2c4*x**p2pwr4
 
 p2ans1 = max(p2pwr1,p2pwr2,p2pwr3,p2pwr4)
 
 # Followup for p2
 p2ans2 = _sage_const_0 
 p2ans3 = _sage_const_0 
 if p2pwr1 == p2ans1:
     p2ans2 = p2ans2 + p2f1
     p2ans3 = p2ans3 + p2c1
 if p2pwr2 == p2ans1:
     p2ans2 = p2ans2 + p2f2
     p2ans3 = p2ans3 + p2c2
 if p2pwr3 == p2ans1:
     p2ans2 = p2ans2 + p2f3
     p2ans3 = p2ans3 + p2c3
 if p2pwr4 == p2ans1:
     p2ans2 = p2ans2 + p2f4
     p2ans3 = p2ans3 + p2c4
 
 #### Problem p3
 p3c1 = RandInt(_sage_const_1 ,_sage_const_10 )
 p3c2 = RandInt(_sage_const_1 ,_sage_const_10 )
 p3c3 = RandInt(_sage_const_1 ,_sage_const_10 )
 p3c4 = RandInt(_sage_const_1 ,_sage_const_10 )
 
 p3pwr1 = RandInt(_sage_const_1 ,_sage_const_10 )
 p3pwr2 = RandInt(_sage_const_1 ,_sage_const_10 )
 p3pwr3 = RandInt(_sage_const_1 ,_sage_const_10 )
 p3pwr4 = RandInt(_sage_const_1 ,_sage_const_10 )
 
 p3f1 = p3c1*x**p3pwr1
 p3f2 = p3c2*x**p3pwr2
 p3f3 = p3c3*x**p3pwr3
 p3f4 = p3c4*x**p3pwr4
 
 p3ans1 = max(p3pwr1,p3pwr2,p3pwr3,p3pwr4)
 
 # Followup for p3
 p3ans2 = _sage_const_0 
 p3ans3 = _sage_const_0 
 if p3pwr1 == p3ans1:
     p3ans2 = p3ans2 + p3f1
     p3ans3 = p3ans3 + p3c1
 if p3pwr2 == p3ans1:
     p3ans2 = p3ans2 + p3f2
     p3ans3 = p3ans3 + p3c2
 if p3pwr3 == p3ans1:
     p3ans2 = p3ans2 + p3f3
     p3ans3 = p3ans3 + p3c3
 if p3pwr4 == p3ans1:
     p3ans2 = p3ans2 + p3f4
     p3ans3 = p3ans3 + p3c4
 
 
 
 
except:
 _st_.goboom(_sage_const_131 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_134 
 _st_.inline(_sage_const_0 , latex(p1f1))
except:
 _st_.goboom(_sage_const_134 )
try:
 _st_.current_tex_line = _sage_const_134 
 _st_.inline(_sage_const_1 , latex(p1f2))
except:
 _st_.goboom(_sage_const_134 )
try:
 _st_.current_tex_line = _sage_const_134 
 _st_.inline(_sage_const_2 , latex(p1f3))
except:
 _st_.goboom(_sage_const_134 )
try:
 _st_.current_tex_line = _sage_const_134 
 _st_.inline(_sage_const_3 , latex(p1f4))
except:
 _st_.goboom(_sage_const_134 )
try:
 _st_.current_tex_line = _sage_const_134 
 _st_.inline(_sage_const_4 , latex(p1ans1))
except:
 _st_.goboom(_sage_const_134 )
try:
 _st_.current_tex_line = _sage_const_140 
 _st_.inline(_sage_const_5 , latex(p1ans1))
except:
 _st_.goboom(_sage_const_140 )
try:
 _st_.current_tex_line = _sage_const_142 
 _st_.inline(_sage_const_6 , latex(p1ans1))
except:
 _st_.goboom(_sage_const_142 )
try:
 _st_.current_tex_line = _sage_const_146 
 _st_.inline(_sage_const_7 , latex(p1ans1))
except:
 _st_.goboom(_sage_const_146 )
try:
 _st_.current_tex_line = _sage_const_154 
 _st_.inline(_sage_const_8 , latex(p1ans2))
except:
 _st_.goboom(_sage_const_154 )
try:
 _st_.current_tex_line = _sage_const_160 
 _st_.inline(_sage_const_9 , latex(p1ans3))
except:
 _st_.goboom(_sage_const_160 )
try:
 _st_.current_tex_line = _sage_const_170 
 _st_.inline(_sage_const_10 , latex(p2f1))
except:
 _st_.goboom(_sage_const_170 )
try:
 _st_.current_tex_line = _sage_const_170 
 _st_.inline(_sage_const_11 , latex(p2f2))
except:
 _st_.goboom(_sage_const_170 )
try:
 _st_.current_tex_line = _sage_const_170 
 _st_.inline(_sage_const_12 , latex(p2f3))
except:
 _st_.goboom(_sage_const_170 )
try:
 _st_.current_tex_line = _sage_const_170 
 _st_.inline(_sage_const_13 , latex(p2f4))
except:
 _st_.goboom(_sage_const_170 )
try:
 _st_.current_tex_line = _sage_const_170 
 _st_.inline(_sage_const_14 , latex(p2ans1))
except:
 _st_.goboom(_sage_const_170 )
try:
 _st_.current_tex_line = _sage_const_176 
 _st_.inline(_sage_const_15 , latex(p2ans1))
except:
 _st_.goboom(_sage_const_176 )
try:
 _st_.current_tex_line = _sage_const_178 
 _st_.inline(_sage_const_16 , latex(p2ans1))
except:
 _st_.goboom(_sage_const_178 )
try:
 _st_.current_tex_line = _sage_const_182 
 _st_.inline(_sage_const_17 , latex(p2ans1))
except:
 _st_.goboom(_sage_const_182 )
try:
 _st_.current_tex_line = _sage_const_190 
 _st_.inline(_sage_const_18 , latex(p2ans2))
except:
 _st_.goboom(_sage_const_190 )
try:
 _st_.current_tex_line = _sage_const_196 
 _st_.inline(_sage_const_19 , latex(p2ans3))
except:
 _st_.goboom(_sage_const_196 )
try:
 _st_.current_tex_line = _sage_const_207 
 _st_.inline(_sage_const_20 , latex(p3f1))
except:
 _st_.goboom(_sage_const_207 )
try:
 _st_.current_tex_line = _sage_const_207 
 _st_.inline(_sage_const_21 , latex(p3f2))
except:
 _st_.goboom(_sage_const_207 )
try:
 _st_.current_tex_line = _sage_const_207 
 _st_.inline(_sage_const_22 , latex(p3f3))
except:
 _st_.goboom(_sage_const_207 )
try:
 _st_.current_tex_line = _sage_const_207 
 _st_.inline(_sage_const_23 , latex(p3f4))
except:
 _st_.goboom(_sage_const_207 )
try:
 _st_.current_tex_line = _sage_const_207 
 _st_.inline(_sage_const_24 , latex(p3ans1))
except:
 _st_.goboom(_sage_const_207 )
try:
 _st_.current_tex_line = _sage_const_213 
 _st_.inline(_sage_const_25 , latex(p3ans1))
except:
 _st_.goboom(_sage_const_213 )
try:
 _st_.current_tex_line = _sage_const_215 
 _st_.inline(_sage_const_26 , latex(p3ans1))
except:
 _st_.goboom(_sage_const_215 )
try:
 _st_.current_tex_line = _sage_const_219 
 _st_.inline(_sage_const_27 , latex(p3ans1))
except:
 _st_.goboom(_sage_const_219 )
try:
 _st_.current_tex_line = _sage_const_227 
 _st_.inline(_sage_const_28 , latex(p3ans2))
except:
 _st_.goboom(_sage_const_227 )
try:
 _st_.current_tex_line = _sage_const_233 
 _st_.inline(_sage_const_29 , latex(p3ans3))
except:
 _st_.goboom(_sage_const_233 )
_st_.endofdoc()

