## -*- encoding: utf-8 -*-
## This file (./transformations-figure4.sagetex.sage) was *autogenerated* from ./transformations-figure4.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('./transformations-figure4', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.endofdoc()
