## -*- encoding: utf-8 -*-

# This file was *autogenerated* from the file rationalRootPractice.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_184 = Integer(184); _sage_const_40 = Integer(40); _sage_const_134 = Integer(134); _sage_const_131 = Integer(131); _sage_const_133 = Integer(133); _sage_const_13 = Integer(13); _sage_const_115 = Integer(115); _sage_const_171 = Integer(171); _sage_const_153 = Integer(153); _sage_const_179 = Integer(179); _sage_const_158 = Integer(158); _sage_const_135 = Integer(135); _sage_const_39 = Integer(39); _sage_const_12 = Integer(12); _sage_const_11 = Integer(11); _sage_const_10 = Integer(10); _sage_const_17 = Integer(17); _sage_const_16 = Integer(16); _sage_const_15 = Integer(15); _sage_const_14 = Integer(14); _sage_const_122 = Integer(122); _sage_const_123 = Integer(123); _sage_const_120 = Integer(120); _sage_const_124 = Integer(124); _sage_const_166 = Integer(166); _sage_const_144 = Integer(144); _sage_const_145 = Integer(145); _sage_const_146 = Integer(146); _sage_const_142 = Integer(142)## This file (rationalRootPractice.sagetex.sage) was *autogenerated* from rationalRootPractice.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('rationalRootPractice', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.current_tex_line = _sage_const_15 
_st_.blockbegin()
try:
 #####Define default Sage variables.
 #Default function variables
 var('x,y,z,X,Y,Z')
 #Default function names
 var('f,g,h,dx,dy,dz,dh,df')
 #Default Wild cards
 w0 = SR.wild(_sage_const_0 )
 
 def RandInt(a,b):
     """ Returns a random integer in [`a`,`b`]. Note that `a` and `b` should be integers themselves to avoid unexpected behavior.
     """
     return QQ(randint(int(a),int(b)))
     # return choice(range(a,b+1))
 
 def NonZeroInt(b,c, avoid = [_sage_const_0 ]):
     """ Returns a random integer in [`b`,`c`] which is not in `av`.
         If `av` is not specified, defaults to a non-zero integer.
     """
     while True:
         a = RandInt(b,c)
         if a not in avoid:
             return a
 
except:
 _st_.goboom(_sage_const_39 )
_st_.blockend()
_st_.current_tex_line = _sage_const_40 
_st_.blockbegin()
try:
 ### Problem p1
 p1c1 = RandInt(-_sage_const_5 ,_sage_const_5 )
 p1c2 = NonZeroInt(-_sage_const_5 ,_sage_const_5 ,[p1c1,-p1c1])
 p1c3 = NonZeroInt(-_sage_const_5 ,_sage_const_5 ,[p1c1,-p1c1, p1c2, -p1c2])
 p1c4 = NonZeroInt(-_sage_const_5 ,_sage_const_5 ,[p1c1,-p1c1, p1c2, -p1c2, p1c3, -p1c3])
 
 p1f1 = expand( (x-p1c1)*(x-p1c2)*(x-p1c3)*(x-p1c4) )
 p1ans1 = min(p1c1, p1c2, p1c3, p1c4)
 p1ans2 = max(p1c1, p1c2, p1c3, p1c4)
 p1ans3 = p1c1+p1c2+p1c3+p1c4
 
 
 ### Problem p2
 p2c1 = RandInt(-_sage_const_5 ,_sage_const_5 )
 p2c2 = NonZeroInt(-_sage_const_5 ,_sage_const_5 ,[p2c1,-p2c1])
 p2c3 = NonZeroInt(-_sage_const_5 ,_sage_const_5 ,[p2c1,-p2c1, p2c2, -p2c2])
 p2c4 = NonZeroInt(-_sage_const_5 ,_sage_const_5 ,[p2c1,-p2c1, p2c2, -p2c2, p2c3, -p2c3])
 
 p2f1 = expand( (x-p2c1)*(x-p2c2)*(x-p2c3)*(x-p2c4) )
 p2ans1 = min(p2c1, p2c2, p2c3, p2c4)
 p2ans2 = max(p2c1, p2c2, p2c3, p2c4)
 p2ans3 = p2c1+p2c2+p2c3+p2c4
 
 
 ### Problem p3
 p3c1 = RandInt(-_sage_const_5 ,_sage_const_5 )
 p3c2 = NonZeroInt(-_sage_const_5 ,_sage_const_5 ,[p3c1,-p3c1])
 p3c3 = NonZeroInt(-_sage_const_5 ,_sage_const_5 ,[p3c1,-p3c1, p3c2, -p3c2])
 p3c4 = NonZeroInt(-_sage_const_5 ,_sage_const_5 ,[p3c1,-p3c1, p3c2, -p3c2, p3c3, -p3c3])
 
 p3f1 = expand( (x-p3c1)*(x-p3c2)*(x-p3c3)*(x-p3c4) )
 p3ans1 = min(p3c1, p3c2, p3c3, p3c4)
 p3ans2 = max(p3c1, p3c2, p3c3, p3c4)
 p3ans3 = p3c1+p3c2+p3c3+p3c4
 
 
 ### Problem p4
 p4c1 = RandInt(_sage_const_1 ,_sage_const_5 )
 p4c2 = RandInt(_sage_const_1 ,_sage_const_5 )
 p4c3 = NonZeroInt(-_sage_const_5 ,_sage_const_5 )
 p4c4 = NonZeroInt(-_sage_const_5 ,_sage_const_5 )
 p4c5 = NonZeroInt(-_sage_const_5 ,_sage_const_5 )
 p4c6 = NonZeroInt(-_sage_const_5 ,_sage_const_5 )
 
 p4f1 = expand( (x**_sage_const_2  + p4c1)*(x**_sage_const_2  + p4c2)*(p4c3*x-p4c4)*(p4c5*x - p4c6) )
 
 p4ans1 = p4c4/p4c3 + p4c6/p4c5
 
 
 ### Problem p5
 p5c1 = RandInt(_sage_const_1 ,_sage_const_5 )
 p5c2 = RandInt(_sage_const_1 ,_sage_const_5 )
 p5c3 = NonZeroInt(-_sage_const_5 ,_sage_const_5 )
 p5c4 = NonZeroInt(-_sage_const_5 ,_sage_const_5 )
 p5c5 = NonZeroInt(-_sage_const_5 ,_sage_const_5 )
 p5c6 = NonZeroInt(-_sage_const_5 ,_sage_const_5 )
 
 p5f1 = expand( (x**_sage_const_2  + p5c1)*(x**_sage_const_2  + p5c2)*(p5c3*x-p5c4)*(p5c5*x - p5c6) )
 
 p5ans1 = p5c4/p5c3 + p5c6/p5c5
 
 
 ### Problem p6
 p6c1 = RandInt(_sage_const_1 ,_sage_const_5 )
 p6c2 = RandInt(_sage_const_1 ,_sage_const_5 )
 p6c3 = NonZeroInt(-_sage_const_5 ,_sage_const_5 )
 p6c4 = NonZeroInt(-_sage_const_5 ,_sage_const_5 )
 p6c5 = NonZeroInt(-_sage_const_5 ,_sage_const_5 )
 p6c6 = NonZeroInt(-_sage_const_5 ,_sage_const_5 )
 
 p6f1 = expand( (x**_sage_const_2  + p6c1)*(x**_sage_const_2  + p6c2)*(p6c3*x-p6c4)*(p6c5*x - p6c6) )
 
 p6ans1 = p6c4/p6c3 + p6c6/p6c5
 
except:
 _st_.goboom(_sage_const_115 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_120 
 _st_.inline(_sage_const_0 , latex(p1f1))
except:
 _st_.goboom(_sage_const_120 )
try:
 _st_.current_tex_line = _sage_const_122 
 _st_.inline(_sage_const_1 , latex(p1ans1))
except:
 _st_.goboom(_sage_const_122 )
try:
 _st_.current_tex_line = _sage_const_123 
 _st_.inline(_sage_const_2 , latex(p1ans2))
except:
 _st_.goboom(_sage_const_123 )
try:
 _st_.current_tex_line = _sage_const_124 
 _st_.inline(_sage_const_3 , latex(p1ans3))
except:
 _st_.goboom(_sage_const_124 )
try:
 _st_.current_tex_line = _sage_const_131 
 _st_.inline(_sage_const_4 , latex(p2f1))
except:
 _st_.goboom(_sage_const_131 )
try:
 _st_.current_tex_line = _sage_const_133 
 _st_.inline(_sage_const_5 , latex(p2ans1))
except:
 _st_.goboom(_sage_const_133 )
try:
 _st_.current_tex_line = _sage_const_134 
 _st_.inline(_sage_const_6 , latex(p2ans2))
except:
 _st_.goboom(_sage_const_134 )
try:
 _st_.current_tex_line = _sage_const_135 
 _st_.inline(_sage_const_7 , latex(p2ans3))
except:
 _st_.goboom(_sage_const_135 )
try:
 _st_.current_tex_line = _sage_const_142 
 _st_.inline(_sage_const_8 , latex(p3f1))
except:
 _st_.goboom(_sage_const_142 )
try:
 _st_.current_tex_line = _sage_const_144 
 _st_.inline(_sage_const_9 , latex(p3ans1))
except:
 _st_.goboom(_sage_const_144 )
try:
 _st_.current_tex_line = _sage_const_145 
 _st_.inline(_sage_const_10 , latex(p3ans2))
except:
 _st_.goboom(_sage_const_145 )
try:
 _st_.current_tex_line = _sage_const_146 
 _st_.inline(_sage_const_11 , latex(p3ans3))
except:
 _st_.goboom(_sage_const_146 )
try:
 _st_.current_tex_line = _sage_const_153 
 _st_.inline(_sage_const_12 , latex(p4f1))
except:
 _st_.goboom(_sage_const_153 )
try:
 _st_.current_tex_line = _sage_const_158 
 _st_.inline(_sage_const_13 , latex(p4ans1))
except:
 _st_.goboom(_sage_const_158 )
try:
 _st_.current_tex_line = _sage_const_166 
 _st_.inline(_sage_const_14 , latex(p5f1))
except:
 _st_.goboom(_sage_const_166 )
try:
 _st_.current_tex_line = _sage_const_171 
 _st_.inline(_sage_const_15 , latex(p5ans1))
except:
 _st_.goboom(_sage_const_171 )
try:
 _st_.current_tex_line = _sage_const_179 
 _st_.inline(_sage_const_16 , latex(p6f1))
except:
 _st_.goboom(_sage_const_179 )
try:
 _st_.current_tex_line = _sage_const_184 
 _st_.inline(_sage_const_17 , latex(p6ans1))
except:
 _st_.goboom(_sage_const_184 )
_st_.endofdoc()

