## -*- encoding: utf-8 -*-
## This file (learningVMemorizing.sagetex.sage) was *autogenerated* from learningVMemorizing.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('learningVMemorizing', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.endofdoc()
